# Generated by Django 5.1.7 on 2025-03-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_label', '0001_initial'),
        ('data_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFrequencyLabelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('label_create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据集创建时间')),
                ('task_execute_time', models.DateTimeField(blank=True, null=True, verbose_name='数据集更新时间')),
                ('out_put_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件输出')),
                ('time_out_time', models.IntegerField(default=3660)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_set', to='data_manage.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='UnsupervisedLabelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('label_create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据集创建时间')),
                ('task_execute_time', models.DateTimeField(blank=True, null=True, verbose_name='数据集更新时间')),
                ('out_put_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件输出')),
                ('time_out_time', models.IntegerField(default=3660)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_set', to='data_manage.dataset')),
            ],
        ),
        migrations.DeleteModel(
            name='DataLabel',
        ),
    ]
