# Generated by Django 5.1.7 on 2025-03-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_label', '0002_timefrequencylabeltask_unsupervisedlabeltask_and_more'),
        ('data_manage', '0002_dataset_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_task_id', models.BigIntegerField(blank=True, null=True, verbose_name='标注任务ID')),
                ('label_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='标注类型')),
                ('label_create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据集创建时间')),
                ('task_execute_time', models.DateTimeField(blank=True, null=True, verbose_name='数据集更新时间')),
                ('out_put_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件输出')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_data_set', to='data_manage.dataset')),
            ],
        ),
    ]
