# Generated by Django 5.1.7 on 2025-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_label', '0003_cleaneddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneddata',
            name='is_executed',
            field=models.BooleanField(default=False, verbose_name='任务是否执行'),
        ),
    ]
