# Generated by Django 5.1.7 on 2025-03-11 07:23

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='数据集名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='数据集描述')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据集创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据集更新时间')),
                ('origin_path', models.TextField(blank=True, null=True, verbose_name='原始文件名称')),
                ('data_set_path', models.FileField(upload_to='data_sets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv', 'xls']), utils.validators.validate_filename, utils.validators.validate_no_executable_files], verbose_name='数据集路径')),
                ('creator', models.IntegerField(verbose_name='创建者')),
            ],
        ),
    ]
