# Generated by Django 5.1.7 on 2025-03-19 15:18

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFrequencyMarkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set_id', models.IntegerField(verbose_name='数据集id')),
                ('input_file', models.FileField(upload_to='data_marks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv', 'xls']), utils.validators.validate_filename, utils.validators.validate_no_executable_files], verbose_name='数据集路径')),
                ('mark_type', models.IntegerField(verbose_name='标注记录类型')),
                ('creator', models.IntegerField(verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='标注记录创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据集更新时间')),
                ('output_dir_path', models.TextField(verbose_name='输出目录路径')),
            ],
        ),
    ]
